FROM python:3.9-slim

WORKDIR /xray

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN mkdir -p app/client

COPY . /xray/app/client

EXPOSE 8000

CMD ["fastapi", "run", "app/client/app.py"]